services:
  - type: web
    name: email-sender-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT src.main:app
    envVars:
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: japanxcollege@gmail.com
      - key: SMTP_PASSWORD
        value: zuth dzji yfrn jbbd
      - key: SENDER_EMAIL
        value: japanxcollege@gmail.com
      - key: SENDER_NAME
        value: JapanXCollege
      - key: FLASK_ENV
        value: production 